name: Release Jerni on PR merged

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

  workflow_dispatch:
    
jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/jerni
        
      - name: Create release and publish to jsr
        uses: ./.github/workflows/release.yml
        with:
          tag: ${{ steps.package-version.outputs.current-version}}