name: Release Jerni on PR merged

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

  workflow_dispatch:
    
jobs:
  get_version:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/jerni

  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    permissions: 
      contents: write
      id-token: write
    needs: get_version

    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.job.get_version.steps.package-version.outputs.current-version}}