name: Pulbish to JSR

on: 
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: false

  workflow_call:
    inputs:
      tag:
        description: 'Tag to publish'
        required: false
        type: string

jobs:
  build:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag }}

      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: chmod +x ./scripts/install-dependencies.sh && ./scripts/install-dependencies.sh

      - name: Publish package
        working-directory: ./packages/jerni
        run: bunx jsr publish --allow-dirty