name: Publish to npm

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        required: false

  workflow_call:
    inputs:
      tag:
        description: "Tag to publish"
        required: false
        type: string

jobs:
  build:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install dependencies
        run: chmod +x ./scripts/install-dependencies.sh && ./scripts/install-dependencies.sh

      - name: Build npm package
        working-directory: ./packages/jerni
        run: |
          chmod +x ./scripts/build-npm.js
          node ./scripts/build-npm.js

      - name: Publish package to npm
        working-directory: ./packages/jerni/dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}