name: Release

on: 
  release:
    types: [published]

jobs:
  build:
    name: Upload release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: cd packages/jerni
      - run: bun link
      - run: cd ../jerni-store-mongodb
      - run: bun link
      - run: cd ../..
      - run: bun install

      - name: Compile executable
        run: bun build ./src/cli.ts --compile --outfile ./src/mycli

      - name: upload built file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./src/mycli
          asset_name: test-cli
          asset_content_type: application/octet-stream

      


  