name: Release

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Upload release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - name: Build CLI
        run: ./scripts/build-cli.sh

      - name: upload built file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/packages/jerni/src/mycli
          asset_name: test-cli
          asset_content_type: application/octet-stream

      


  