name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
      publish_npm:
        description: 'Publish to npm'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

  workflow_call:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        type: string
      publish_npm:
        description: 'Publish to npm'
        required: false
        default: 'true'
        type: string

jobs:
  build:
    uses: ./.github/workflows/release_binary_jerni_files.yml
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.inputs.tag }}

  publish_jsr:
    # use the published_jsr.yml workflow to publish to JSR
    needs: build
    uses: ./.github/workflows/publish_jsr.yml
    permissions: 
      contents: read
      id-token: write
    with:
      tag: ${{ github.event.inputs.tag }}
      
  publish_npm:
    # use the publish_npm.yml workflow to publish to npm
    needs: build
    if: ${{ github.event.inputs.publish_npm != 'false' }}
    uses: ./.github/workflows/publish_npm.yml
    permissions: 
      contents: read
      id-token: write
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
