name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

  workflow_call:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        type: string

jobs:
  build:
    name: Upload release asset
    uses: ./.github/workflows/release_binary_jerni_files.yml
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.inputs.tag }}

  publish:
    # use the published_jsr.yml workflow to publish to JSR
    needs: build
    uses: ./.github/workflows/publish_jsr.yml
    permissions: 
      contents: read
      id-token: write
    with:
      tag: ${{ github.event.inputs.tag }}
